dir: mocks
filename: '{{.InterfaceName}}.go'
structname: '{{.InterfaceName}}'
pkgname: mocks
formatter: goimports
log-level: info
packages:
  github.com/tahardi/little-things/backend/internal/version:
  github.com/tahardi/little-things/backend/internal/llm:
    interfaces:
      Client:
  github.com/tahardi/little-things/backend/internal/transcribe:
    interfaces:
      Transcriber:
  github.com/tahardi/little-things/backend/internal/server:
    interfaces:
      FieldParser:
      NoteExtractor:
      GiftGenerator:
