// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

type Client_Expecter struct {
	mock *mock.Mock
}

func (_m *Client) EXPECT() *Client_Expecter {
	return &Client_Expecter{mock: &_m.Mock}
}

// Structured provides a mock function for the type Client
func (_mock *Client) Structured(ctx context.Context, system string, user string, schema map[string]any, out any) error {
	ret := _mock.Called(ctx, system, user, schema, out)

	if len(ret) == 0 {
		panic("no return value specified for Structured")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, map[string]any, any) error); ok {
		r0 = returnFunc(ctx, system, user, schema, out)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Client_Structured_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Structured'
type Client_Structured_Call struct {
	*mock.Call
}

// Structured is a helper method to define mock.On call
//   - ctx context.Context
//   - system string
//   - user string
//   - schema map[string]any
//   - out any
func (_e *Client_Expecter) Structured(ctx any, system any, user any, schema any, out any) *Client_Structured_Call {
	return &Client_Structured_Call{Call: _e.mock.On("Structured", ctx, system, user, schema, out)}
}

func (_c *Client_Structured_Call) Run(run func(ctx context.Context, system string, user string, schema map[string]any, out any)) *Client_Structured_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]any
		if args[3] != nil {
			arg3 = args[3].(map[string]any)
		}
		var arg4 any
		if args[4] != nil {
			arg4 = args[4].(any)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *Client_Structured_Call) Return(err error) *Client_Structured_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Client_Structured_Call) RunAndReturn(run func(ctx context.Context, system string, user string, schema map[string]any, out any) error) *Client_Structured_Call {
	_c.Call.Return(run)
	return _c
}
