// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
	"github.com/tahardi/little-things/backend/internal/model"
)

// NewFieldParser creates a new instance of FieldParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFieldParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *FieldParser {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &FieldParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// FieldParser is an autogenerated mock type for the FieldParser type
type FieldParser struct {
	mock.Mock
}

type FieldParser_Expecter struct {
	mock *mock.Mock
}

func (_m *FieldParser) EXPECT() *FieldParser_Expecter {
	return &FieldParser_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function for the type FieldParser
func (_mock *FieldParser) Parse(ctx context.Context, field model.Field, transcript string) (json.RawMessage, error) {
	ret := _mock.Called(ctx, field, transcript)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Field, string) (json.RawMessage, error)); ok {
		return returnFunc(ctx, field, transcript)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.Field, string) json.RawMessage); ok {
		r0 = returnFunc(ctx, field, transcript)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.Field, string) error); ok {
		r1 = returnFunc(ctx, field, transcript)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// FieldParser_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type FieldParser_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - ctx context.Context
//   - field model.Field
//   - transcript string
func (_e *FieldParser_Expecter) Parse(ctx any, field any, transcript any) *FieldParser_Parse_Call {
	return &FieldParser_Parse_Call{Call: _e.mock.On("Parse", ctx, field, transcript)}
}

func (_c *FieldParser_Parse_Call) Run(run func(ctx context.Context, field model.Field, transcript string)) *FieldParser_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.Field
		if args[1] != nil {
			arg1 = args[1].(model.Field)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *FieldParser_Parse_Call) Return(rawMessage json.RawMessage, err error) *FieldParser_Parse_Call {
	_c.Call.Return(rawMessage, err)
	return _c
}

func (_c *FieldParser_Parse_Call) RunAndReturn(run func(ctx context.Context, field model.Field, transcript string) (json.RawMessage, error)) *FieldParser_Parse_Call {
	_c.Call.Return(run)
	return _c
}
