// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tahardi/little-things/backend/internal/model"
)

// NewGiftGenerator creates a new instance of GiftGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGiftGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *GiftGenerator {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &GiftGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// GiftGenerator is an autogenerated mock type for the GiftGenerator type
type GiftGenerator struct {
	mock.Mock
}

type GiftGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *GiftGenerator) EXPECT() *GiftGenerator_Expecter {
	return &GiftGenerator_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type GiftGenerator
func (_mock *GiftGenerator) Generate(ctx context.Context, req model.GiftsRequest) (model.GiftsResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 model.GiftsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.GiftsRequest) (model.GiftsResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.GiftsRequest) model.GiftsResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		r0 = ret.Get(0).(model.GiftsResponse)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.GiftsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// GiftGenerator_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type GiftGenerator_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - ctx context.Context
//   - req model.GiftsRequest
func (_e *GiftGenerator_Expecter) Generate(ctx any, req any) *GiftGenerator_Generate_Call {
	return &GiftGenerator_Generate_Call{Call: _e.mock.On("Generate", ctx, req)}
}

func (_c *GiftGenerator_Generate_Call) Run(run func(ctx context.Context, req model.GiftsRequest)) *GiftGenerator_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.GiftsRequest
		if args[1] != nil {
			arg1 = args[1].(model.GiftsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *GiftGenerator_Generate_Call) Return(giftsResponse model.GiftsResponse, err error) *GiftGenerator_Generate_Call {
	_c.Call.Return(giftsResponse, err)
	return _c
}

func (_c *GiftGenerator_Generate_Call) RunAndReturn(run func(ctx context.Context, req model.GiftsRequest) (model.GiftsResponse, error)) *GiftGenerator_Generate_Call {
	_c.Call.Return(run)
	return _c
}
