// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/tahardi/little-things/backend/internal/model"
)

// NewNoteExtractor creates a new instance of NoteExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewNoteExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *NoteExtractor {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &NoteExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// NoteExtractor is an autogenerated mock type for the NoteExtractor type
type NoteExtractor struct {
	mock.Mock
}

type NoteExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *NoteExtractor) EXPECT() *NoteExtractor_Expecter {
	return &NoteExtractor_Expecter{mock: &_m.Mock}
}

// Extract provides a mock function for the type NoteExtractor
func (_mock *NoteExtractor) Extract(ctx context.Context, transcript string, people []model.Person) (model.NoteResult, error) {
	ret := _mock.Called(ctx, transcript, people)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 model.NoteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.Person) (model.NoteResult, error)); ok {
		return returnFunc(ctx, transcript, people)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []model.Person) model.NoteResult); ok {
		r0 = returnFunc(ctx, transcript, people)
	} else {
		r0 = ret.Get(0).(model.NoteResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []model.Person) error); ok {
		r1 = returnFunc(ctx, transcript, people)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// NoteExtractor_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type NoteExtractor_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - ctx context.Context
//   - transcript string
//   - people []model.Person
func (_e *NoteExtractor_Expecter) Extract(ctx any, transcript any, people any) *NoteExtractor_Extract_Call {
	return &NoteExtractor_Extract_Call{Call: _e.mock.On("Extract", ctx, transcript, people)}
}

func (_c *NoteExtractor_Extract_Call) Run(run func(ctx context.Context, transcript string, people []model.Person)) *NoteExtractor_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []model.Person
		if args[2] != nil {
			arg2 = args[2].([]model.Person)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *NoteExtractor_Extract_Call) Return(noteResult model.NoteResult, err error) *NoteExtractor_Extract_Call {
	_c.Call.Return(noteResult, err)
	return _c
}

func (_c *NoteExtractor_Extract_Call) RunAndReturn(run func(ctx context.Context, transcript string, people []model.Person) (model.NoteResult, error)) *NoteExtractor_Extract_Call {
	_c.Call.Return(run)
	return _c
}
