// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewTranscriber creates a new instance of Transcriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTranscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *Transcriber {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &Transcriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// Transcriber is an autogenerated mock type for the Transcriber type
type Transcriber struct {
	mock.Mock
}

type Transcriber_Expecter struct {
	mock *mock.Mock
}

func (_m *Transcriber) EXPECT() *Transcriber_Expecter {
	return &Transcriber_Expecter{mock: &_m.Mock}
}

// Transcribe provides a mock function for the type Transcriber
func (_mock *Transcriber) Transcribe(ctx context.Context, audioPath string) (string, error) {
	ret := _mock.Called(ctx, audioPath)

	if len(ret) == 0 {
		panic("no return value specified for Transcribe")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, audioPath)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, audioPath)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, audioPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// Transcriber_Transcribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Transcribe'
type Transcriber_Transcribe_Call struct {
	*mock.Call
}

// Transcribe is a helper method to define mock.On call
//   - ctx context.Context
//   - audioPath string
func (_e *Transcriber_Expecter) Transcribe(ctx any, audioPath any) *Transcriber_Transcribe_Call {
	return &Transcriber_Transcribe_Call{Call: _e.mock.On("Transcribe", ctx, audioPath)}
}

func (_c *Transcriber_Transcribe_Call) Run(run func(ctx context.Context, audioPath string)) *Transcriber_Transcribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Transcriber_Transcribe_Call) Return(s string, err error) *Transcriber_Transcribe_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *Transcriber_Transcribe_Call) RunAndReturn(run func(ctx context.Context, audioPath string) (string, error)) *Transcriber_Transcribe_Call {
	_c.Call.Return(run)
	return _c
}
